# Generated by Django 5.0.4 on 2024-05-08 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passport_user_alter_personalaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(max_length=50, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(max_length=50, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='profit_year',
            field=models.CharField(max_length=50, verbose_name='Доход за год'),
        ),
        migrations.AlterField(
            model_name='company',
            name='revenue_year',
            field=models.CharField(max_length=50, verbose_name='Выручка за год'),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passport',
            name='department_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='passport',
            name='series',
            field=models.CharField(max_length=4),
        ),
    ]
