# Generated by Django 5.0.4 on 2024-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_company_inn_alter_company_kpp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
